In [1]:
import numpy as np

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
array=np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array[0]

array([1, 2, 3])

In [12]:
array[1]

array([4, 5, 6])

In [13]:
array[0,:2]

array([1, 2])

In [17]:
array[0,2] #row index, col index

3

In [19]:
array.ndim #차원의 수

2

In [20]:
array.shape #각 차원의 길이

(2, 3)

In [21]:
array.dtype

dtype('int32')

In [22]:
array.sum()

21

In [23]:
array.min()

1

In [24]:
array.max()

6

In [25]:
array.mean()

3.5

In [26]:
array.std()

1.707825127659933